[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs"]
  included_files = ["views/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true 